version: "3.8"
services:
  nginx_for_emby:
    image: nginx:latest
    container_name: embygroup.nginx_for_emby
    network_mode: host
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/embyCache:/var/cache/nginx/emby
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped
